function rocketPlantValidateConfig(Rocket)
%ROCKETPLANTVALIDATECONFIG Reject incomplete or inconsistent physical inputs.
    names = fieldnames(Rocket);
    for k = 1:numel(names)
        value = Rocket.(names{k});
        assert(isa(value,'double') && all(isfinite(value(:))), ...
            'RocketPlant:InvalidParameter','Rocket.%s must be finite double.',names{k});
    end
    scalarNames = {'Ts','MaxStep','IgnitionTime','RailLength', ...
        'LaunchInclination','LaunchHeading','LaunchRoll','Latitude','Longitude', ...
        'AltitudeMSL','DryMass','PropellantMass','ReferenceArea','ReferenceLength', ...
        'AeroEnabled','BodyRadius','NoseLength','NoseBaseRadius','NoseTipZ', ...
        'NoseCPFraction','FinNumber','FinRootChord','FinTipChord','FinSpan', ...
        'FinSweepLength','FinLeadingEdgeZ','FinCant','TailLength', ...
        'TailTopRadius','TailBottomRadius','TailTopZ', ...
        'DrogueLag','DrogueCdS','DrogueInflationTime','MainAltitudeAGL', ...
        'MainLag','MainCdS','MainInflationTime'};
    for k = 1:numel(scalarNames)
        assert(isscalar(Rocket.(scalarNames{k})), ...
            'RocketPlant:InvalidSize','Rocket.%s must be scalar.',scalarNames{k});
    end
    vectorNames = {'DryInertia','PropellantInertia','ThrustDirection', ...
        'ThrustOffset','NozzleGyration','AngularDamping', ...
        'DrogueAttachment','MainAttachment','IMUOffset'};
    for k = 1:numel(vectorNames)
        assert(isequal(size(Rocket.(vectorNames{k})),[3 1]), ...
            'RocketPlant:InvalidSize','Rocket.%s must be a 3-by-1 column.',vectorNames{k});
    end
    curveNames = {'ThrustTime','ThrustForce','ThrustCumulativeImpulse', ...
        'AeroMach','AeroCdPowered','AeroCdCoast','WindAltitude'};
    for k = 1:numel(curveNames)
        assert(iscolumn(Rocket.(curveNames{k})) && numel(Rocket.(curveNames{k}))>=2, ...
            'RocketPlant:InvalidSize','Rocket.%s must be a column with at least two rows.',curveNames{k});
    end
    assert(abs(Rocket.Latitude)<=pi/2 && abs(Rocket.Longitude)<=pi);
    assert(Rocket.Ts>0 && Rocket.MaxStep>0 && Rocket.MaxStep<=Rocket.Ts);
    assert(Rocket.IgnitionTime>=0 && Rocket.RailLength>=0);
    assert(Rocket.LaunchInclination>0 && Rocket.LaunchInclination<=pi/2);
    assert(Rocket.DryMass>0 && Rocket.PropellantMass>=0);
    assert(all(Rocket.DryInertia>0) && all(Rocket.PropellantInertia>=0));
    assert(Rocket.ReferenceArea>0 && Rocket.ReferenceLength>0);
    assert(all(Rocket.AngularDamping>=0));
    assert(Rocket.AeroEnabled==0 || Rocket.AeroEnabled==1);
    assert(Rocket.BodyRadius>0 && ...
        abs(Rocket.ReferenceArea-pi*Rocket.BodyRadius^2)<1e-12);
    assert(Rocket.NoseLength>=0 && Rocket.NoseBaseRadius>=0 && ...
        Rocket.NoseCPFraction>=0 && Rocket.NoseCPFraction<=1);
    assert(Rocket.FinNumber>=3 && Rocket.FinNumber==fix(Rocket.FinNumber));
    assert(Rocket.FinRootChord>0 && Rocket.FinTipChord>=0 && Rocket.FinSpan>0);
    assert(abs(Rocket.FinCant)<pi/2);
    assert(Rocket.TailLength>=0 && Rocket.TailTopRadius>=0 && ...
        Rocket.TailBottomRadius>=0 && Rocket.TailTopRadius+Rocket.TailBottomRadius>0);
    n=size(Rocket.AeroSurfaceCP,1);
    assert(n>=1 && size(Rocket.AeroSurfaceCP,2)==3);
    surfaceNames={'AeroSurfaceArea','AeroSurfaceDiameter','AeroSurfaceCNa', ...
        'AeroFinPlanform','AeroFinLiftNumerator','AeroFinLiftMultiplier', ...
        'AeroRollForceScale','AeroRollDampScale','AeroSurfaceCant'};
    for k=1:numel(surfaceNames)
        assert(isequal(size(Rocket.(surfaceNames{k})),[n 1]), ...
            'RocketPlant:InvalidSize','Rocket.%s must match the CP row count.',surfaceNames{k});
    end
    assert(all(Rocket.AeroSurfaceArea>0) && all(Rocket.AeroSurfaceDiameter>0));
    % A narrowing tail has a negative normal-force slope: preserve its sign.
    assert(all(Rocket.AeroFinPlanform>=0) && all(Rocket.AeroFinLiftNumerator>=0) && ...
        all(Rocket.AeroFinLiftMultiplier>=0) && all(Rocket.AeroRollDampScale>=0));
    assert(norm(Rocket.ThrustDirection)>0 && all(Rocket.NozzleGyration>=0));
    assert(all(diff(Rocket.ThrustTime)>0) && Rocket.ThrustTime(1)==0);
    assert(numel(Rocket.ThrustTime)==numel(Rocket.ThrustForce));
    assert(all(Rocket.ThrustForce>=0) && Rocket.ThrustForce(1)==0 && Rocket.ThrustForce(end)==0);
    assert(trapz(Rocket.ThrustTime,Rocket.ThrustForce)>0);
    expected = cumtrapz(Rocket.ThrustTime,Rocket.ThrustForce);
    expected = expected/expected(end);
    assert(isequal(size(expected),size(Rocket.ThrustCumulativeImpulse)) && ...
        max(abs(expected-Rocket.ThrustCumulativeImpulse))<1e-10, ...
        'RocketPlant:ImpulseMismatch','Recompute normalized thrust cumulative impulse.');
    assert(all(diff(Rocket.AeroMach)>0) && Rocket.AeroMach(1)==0);
    assert(numel(Rocket.AeroMach)==numel(Rocket.AeroCdPowered) && ...
        numel(Rocket.AeroMach)==numel(Rocket.AeroCdCoast));
    assert(all(Rocket.AeroCdPowered>=0) && all(Rocket.AeroCdCoast>=0));
    assert(all(diff(Rocket.WindAltitude)>0) && size(Rocket.WindNED,2)==3 && ...
        size(Rocket.WindNED,1)==numel(Rocket.WindAltitude));
    assert(Rocket.DrogueLag>=0 && Rocket.MainLag>=0 && Rocket.MainAltitudeAGL>=0);
    assert(Rocket.DrogueCdS>=0 && Rocket.MainCdS>=0);
    assert(Rocket.DrogueInflationTime>0 && Rocket.MainInflationTime>0);
end
