function rocketWeatherValidateConfig(Weather,requireProfile)
%ROCKETWEATHERVALIDATECONFIG Check the flat numeric weather configuration.
% requireProfile=false validates inputs before building the pressure table.
% A custom sounding may replace the four profile columns after initialization.
if nargin<2, requireProfile=true; end
if isempty(Weather), return; end
assert(isstruct(Weather) && isscalar(Weather), ...
    'RocketWeather:InvalidConfiguration','Weather must be a scalar structure.');
scalarFields={'UseProfile','StationAltitudeMSL','StationTemperatureK', ...
    'StationPressurePa','StationRelativeHumidity','LapseRateOffset', ...
    'HumidityScaleHeight','ProfileMinAltitudeMSL','ProfileMaxAltitudeMSL', ...
    'ProfileStepAltitude','GustEnabled','GustStartTime','GustRampTime', ...
    'DiscreteGustStartTime','DiscreteGustDuration'};
for k=1:numel(scalarFields)
    name=scalarFields{k};
    assert(isfield(Weather,name) && (isnumeric(Weather.(name)) || ...
        islogical(Weather.(name))) && isreal(Weather.(name)) && ...
        isscalar(Weather.(name)) && isfinite(Weather.(name)), ...
        'RocketWeather:InvalidScalar','Weather.%s must be a finite real scalar.',name);
end
assert(any(Weather.UseProfile==[0 1]) && any(Weather.GustEnabled==[0 1]), ...
    'RocketWeather:InvalidSwitch','UseProfile and GustEnabled must be 0 or 1.');
assert(Weather.ProfileMinAltitudeMSL>=-5000 && ...
    Weather.ProfileMaxAltitudeMSL<=30000 && ...
    Weather.ProfileMaxAltitudeMSL>Weather.ProfileMinAltitudeMSL && ...
    Weather.StationAltitudeMSL>=Weather.ProfileMinAltitudeMSL && ...
    Weather.StationAltitudeMSL<=Weather.ProfileMaxAltitudeMSL, ...
    'RocketWeather:InvalidAltitude', ...
    'Profile range must contain the station and stay within -5000 to 30000 m MSL.');
assert(Weather.StationTemperatureK>=180 && Weather.StationTemperatureK<=350 && ...
    Weather.StationPressurePa>=1000 && Weather.StationPressurePa<=120000 && ...
    Weather.StationRelativeHumidity>=0 && Weather.StationRelativeHumidity<=1, ...
    'RocketWeather:InvalidStation', ...
    'Station needs T in [180,350] K, P in [1000,120000] Pa and RH in [0,1].');
assert(abs(Weather.LapseRateOffset)<=0.01 && Weather.HumidityScaleHeight>0 && ...
    Weather.ProfileStepAltitude>0 && Weather.ProfileStepAltitude<=1000 && ...
    (Weather.ProfileMaxAltitudeMSL-Weather.ProfileMinAltitudeMSL)/ ...
    Weather.ProfileStepAltitude<=200000, ...
    'RocketWeather:InvalidProfileGrid', ...
    'Use a positive scale height, |lapse offset| <= 0.01 K/m and 0 < grid step <= 1000 m.');
arrayFields={'WindAltitudeAGL','WindNED','GustRmsNED', ...
    'GustFrequenciesHz','GustWeights','GustPhases','DiscreteGustPeakNED'};
for k=1:numel(arrayFields)
    name=arrayFields{k};
    assert(isfield(Weather,name) && isnumeric(Weather.(name)) && ...
        isreal(Weather.(name)) && ~isempty(Weather.(name)) && ...
        all(isfinite(Weather.(name)(:))), ...
        'RocketWeather:InvalidArray','Weather.%s must be finite real numeric data.',name);
end
assert(iscolumn(Weather.WindAltitudeAGL) && ...
    all(Weather.WindAltitudeAGL>=0) && all(diff(Weather.WindAltitudeAGL)>0) && ...
    size(Weather.WindNED,1)==numel(Weather.WindAltitudeAGL) && ...
    size(Weather.WindNED,2)==3, ...
    'RocketWeather:InvalidWind','Wind needs increasing AGL knots and an Nx3 NED velocity table.');
assert(isequal(size(Weather.GustRmsNED),[3 1]) && all(Weather.GustRmsNED>=0) && ...
    isequal(size(Weather.DiscreteGustPeakNED),[3 1]), ...
    'RocketWeather:InvalidGustAmplitude','Gust RMS and discrete peak must be 3x1 NED vectors; RMS is nonnegative.');
n=numel(Weather.GustFrequenciesHz);
assert(iscolumn(Weather.GustFrequenciesHz) && ...
    all(Weather.GustFrequenciesHz>0) && all(diff(Weather.GustFrequenciesHz)>0) && ...
    iscolumn(Weather.GustWeights) && numel(Weather.GustWeights)==n && ...
    all(Weather.GustWeights>=0) && isfinite(norm(Weather.GustWeights)) && ...
    norm(Weather.GustWeights)>0 && ...
    isequal(size(Weather.GustPhases),[n 3]) && ...
    Weather.GustRampTime>0 && Weather.DiscreteGustDuration>0, ...
    'RocketWeather:InvalidGustSeries', ...
    'Gusts need increasing positive frequencies, nonzero weights, Kx3 phases and positive ramp/duration.');
profileFields={'ProfileAltitudeMSL','ProfilePressurePa', ...
    'ProfileTemperatureK','ProfileRelativeHumidity'};
present=isfield(Weather,profileFields);
if requireProfile && (Weather.UseProfile==1 || any(present))
    assert(all(present),'RocketWeather:MissingProfile','Build all four weather profile columns before use.');
    count=numel(Weather.ProfileAltitudeMSL);
    assert(count>=2,'RocketWeather:InvalidProfile','At least two profile altitude knots are required.');
    for k=1:numel(profileFields)
        name=profileFields{k};
        assert(isnumeric(Weather.(name)) && isreal(Weather.(name)) && ...
            iscolumn(Weather.(name)) && numel(Weather.(name))==count && ...
            all(isfinite(Weather.(name))), ...
            'RocketWeather:InvalidProfile','Weather.%s must be a finite matched column.',name);
    end
    assert(all(diff(Weather.ProfileAltitudeMSL)>0) && ...
        Weather.ProfileAltitudeMSL(1)<=Weather.ProfileMinAltitudeMSL && ...
        Weather.ProfileAltitudeMSL(end)>=Weather.ProfileMaxAltitudeMSL && ...
        all(Weather.ProfilePressurePa>0) && all(diff(Weather.ProfilePressurePa)<0) && ...
        all(Weather.ProfileTemperatureK>=180 & Weather.ProfileTemperatureK<=350) && ...
        all(Weather.ProfileRelativeHumidity>=0 & Weather.ProfileRelativeHumidity<=1), ...
        'RocketWeather:InvalidProfile','Profile altitude, pressure, temperature or RH is outside physical bounds.');
    tc=Weather.ProfileTemperatureK-273.15;
    e=Weather.ProfileRelativeHumidity.*611.*10.^(7.5.*tc./(237.3+tc));
    assert(all(e<Weather.ProfilePressurePa), ...
        'RocketWeather:InvalidVaporPressure','Water vapor partial pressure must remain below total pressure.');
end
end
