function summary = summarizeRocketWeather(out,Rocket,Weather,baseline,outputDirectory)
%SUMMARIZEROCKETWEATHER Export weather truth and compare integrated flights.
% Weather truth schema (SI, local NED): [wind N/E/D, density, pressure,
% sound speed, temperature K, relative humidity fraction, gust N/E/D].
% Statistics and plots use airborne phases 1..4; navigation measurements and
% configuration are only read. Configured weather is a synthetic example.

    assert(isstruct(baseline) && all(isfield(baseline,{'out','Rocket'})), ...
        'RocketPlant:MissingBaseline','Baseline must contain out and Rocket.');
    [t,x]=loggedTruth(out);
    [oldT,oldX]=loggedTruth(baseline.out);
    weatherTime=out.WeatherTruth.Time(:);
    weather=out.WeatherTruth.Data;
    debugTime=out.RocketPlantDebug.Time(:);
    debug=out.RocketPlantDebug.Data;
    assert(size(weather,2)==11 && size(weather,1)==numel(t) && ...
        numel(weatherTime)==numel(t) && all(isfinite(weather(:))) && ...
        all(isfinite(weatherTime)) && max(abs(weatherTime-t))<1e-9, ...
        'RocketPlant:InvalidWeatherTruth', ...
        'Expected finite Nx11 weather truth aligned with the plant state.');
    assert(size(debug,2)==18 && size(debug,1)==numel(t) && ...
        numel(debugTime)==numel(t) && all(isfinite(debug(:))) && ...
        all(isfinite(debugTime)) && max(abs(debugTime-t))<1e-9, ...
        'RocketPlant:InvalidWeatherDebug', ...
        'Expected finite Nx18 plant debug aligned with the weather truth.');
    assert(all(weather(:,4)>0) && all(weather(:,5)>0) && ...
        all(weather(:,6)>0) && all(weather(:,7)>0) && ...
        all(weather(:,8)>=0 & weather(:,8)<=1), ...
        'RocketPlant:UnphysicalWeather', ...
        'Density, pressure, sound speed and Kelvin temperature must be positive; RH must be in [0,1].');
    assert(all(debug(:,8)>0),'RocketPlant:UnphysicalDebugPressure', ...
        'Plant debug pressure must be positive.');
    pressureRelativeError=max(abs(weather(:,5)-debug(:,8))./abs(debug(:,8)));
    assert(pressureRelativeError<1e-9,'RocketPlant:WeatherPressureMismatch', ...
        'Logged weather and plant pressure must agree to relative tolerance 1e-9.');
    inFlight=x(:,14)>=1 & x(:,14)<=4;
    oldInFlight=oldX(:,14)>=1 & oldX(:,14)<=4;
    assert(any(inFlight) && any(oldInFlight),'RocketPlant:NoWeatherFlight', ...
        'Both runs must contain airborne phases 1..4.');
    flightWeather=weather(inFlight,:);
    flightTime=t(inFlight)-Rocket.IgnitionTime;
    flightHeight=-x(inFlight,3);
    wind=flightWeather(:,1:3);
    gust=flightWeather(:,9:11);
    windSpeed=vecnorm(wind,2,2);
    gustMagnitude=vecnorm(gust,2,2);

    newMetrics=flightMetrics(out,t,x,Rocket);
    oldMetrics=flightMetrics(baseline.out,oldT,oldX,baseline.Rocket);
    summary=struct('SyntheticWeatherConfiguration',true, ...
        'CoordinateFrame','Local North East Down', ...
        'StatisticsPhases',[1;2;3;4], ...
        'FlightSampleCount',sum(inFlight), ...
        'FlightTimeSinceIgnitionRangeS',[min(flightTime);max(flightTime)], ...
        'FlightHeightAGLRangeM',[min(flightHeight);max(flightHeight)], ...
        'TemperatureRangeK',columnRange(flightWeather(:,7)), ...
        'PressureRangePa',columnRange(flightWeather(:,5)), ...
        'DensityRangeKgpm3',columnRange(flightWeather(:,4)), ...
        'SoundSpeedRangeMps',columnRange(flightWeather(:,6)), ...
        'RelativeHumidityRangeFraction',columnRange(flightWeather(:,8)), ...
        'WindNEDMinimumMps',min(wind,[],1).', ...
        'WindNEDMaximumMps',max(wind,[],1).', ...
        'MaximumWindVectorNormMps',max(windSpeed), ...
        'MaximumGustVectorNormMps',max(gustMagnitude), ...
        'GustVectorRmsMps',sqrt(mean(gustMagnitude.^2)), ...
        'GustNEDRmsMps',sqrt(mean(gust.^2,1)).', ...
        'MaximumAbsoluteGustNEDMps',max(abs(gust),[],1).', ...
        'MaximumPressureRelativeDifference',pressureRelativeError, ...
        'Baseline',oldMetrics,'ConfiguredWeather',newMetrics, ...
        'ApogeeHeightChangeM',newMetrics.ApogeeHeightAGLM-oldMetrics.ApogeeHeightAGLM, ...
        'PeakSpeedChangeMps',newMetrics.PeakSpeedMps-oldMetrics.PeakSpeedMps, ...
        'LandingTimeChangeS',newMetrics.LandingTimeSinceIgnitionS-oldMetrics.LandingTimeSinceIgnitionS, ...
        'FlightPositionRmsErrorChangeM',newMetrics.FlightPositionRmsErrorM-oldMetrics.FlightPositionRmsErrorM, ...
        'LaunchPeakPositionErrorChangeM',newMetrics.LaunchPeakPositionErrorM-oldMetrics.LaunchPeakPositionErrorM);
    if isfield(Weather,'UseProfile')
        assert(isscalar(Weather.UseProfile) && isfinite(Weather.UseProfile) && ...
            any(Weather.UseProfile==[0 1]),'RocketPlant:InvalidWeatherProfileFlag', ...
            'Weather.UseProfile must be a logical or numeric scalar 0 or 1.');
        summary.UseWeatherProfile=logical(Weather.UseProfile);
    end
    if ~isfolder(outputDirectory), mkdir(outputDirectory); end
    fid=fopen(fullfile(outputDirectory,'rocket-weather-summary.json'),'w');
    assert(fid>=0,'RocketPlant:WeatherReportWriteFailure','Cannot write the weather report.');
    cleanup=onCleanup(@() fclose(fid));
    fprintf(fid,'%s\n',jsonencode(summary,'PrettyPrint',true));
    trace=array2table([t(inFlight),flightTime,flightHeight,x(inFlight,14),flightWeather], ...
        'VariableNames',{'SimulationTime_s','TimeSinceIgnition_s','HeightAGL_m','Phase', ...
        'WindNorth_mps','WindEast_mps','WindDown_mps','Density_kgpm3', ...
        'Pressure_Pa','SoundSpeed_mps','Temperature_K','RelativeHumidity_fraction', ...
        'GustNorth_mps','GustEast_mps','GustDown_mps'});
    writetable(trace,fullfile(outputDirectory,'rocket-weather-trace.csv'));

    f=figure('Color','white','Name','Rocket weather and flight comparison', ...
        'Visible','off','Position',[100 100 1100 760]);
    figureCleanup=onCleanup(@() close(f));
    layout=tiledlayout(f,2,2,'TileSpacing','compact','Padding','compact');
    nexttile(layout);
    plot(flightTime,wind,'LineWidth',1.1);
    grid on; xlabel('Time since ignition (s)'); ylabel('Wind (m/s)');
    legend('North','East','Down','Location','best'); title('Logged wind');
    nexttile(layout);
    plot(flightTime,gust,'LineWidth',1.1);
    grid on; xlabel('Time since ignition (s)'); ylabel('Gust (m/s)');
    legend('North','East','Down','Location','best'); title('Explicit gust input');
    nexttile(layout);
    [sortedHeight,heightOrder]=sort(flightHeight);
    yyaxis left;
    plot(sortedHeight,flightWeather(heightOrder,7)-273.15,'LineWidth',1.3);
    ylabel('Temperature (°C)');
    yyaxis right;
    plot(sortedHeight,100*flightWeather(heightOrder,8),'LineWidth',1.3);
    ylabel('Relative humidity (%)');
    grid on; xlabel('Height AGL (m)'); title('Sampled thermodynamic profile');
    legend('Temperature','Relative humidity','Location','best');
    nexttile(layout);
    plot(oldT(oldInFlight)-baseline.Rocket.IgnitionTime,-oldX(oldInFlight,3), ...
        flightTime,flightHeight,'LineWidth',1.4);
    grid on; xlabel('Time since ignition (s)'); ylabel('Height AGL (m)');
    legend('Baseline atmosphere','Configured weather','Location','best');
    title('Integrated flight response');
    title(layout,'Synthetic weather configuration: airborne samples only');
    exportgraphics(f,fullfile(outputDirectory,'rocket-weather-comparison.png'),'Resolution',170);
    exportgraphics(f,fullfile(outputDirectory,'rocket-weather-comparison.pdf'),'ContentType','vector');
end

function [t,x]=loggedTruth(out)
    t=out.RocketPlantState.Time(:);
    x=out.RocketPlantState.Data;
    assert(size(x,2)==17 && size(x,1)==numel(t) && all(isfinite(x(:))) && ...
        all(isfinite(t)) && all(diff(t)>0),'RocketPlant:InvalidWeatherPlantState', ...
        'Expected finite 17-state truth logging with strictly increasing time.');
    assert(all(x(:,14)>=0 & x(:,14)<=5 & x(:,14)==fix(x(:,14))), ...
        'RocketPlant:InvalidWeatherFlightPhase','Plant phases must be integers from 0 through 5.');
end

function range=columnRange(values)
    range=[min(values);max(values)];
end

function metrics=flightMetrics(out,t,x,Rocket)
    estimated=[out.North.signals.values(:),out.East.signals.values(:), ...
        out.Up.signals.values(:)];
    truth=[out.NorthTrue.signals.values(:),out.EastTrue.signals.values(:), ...
        out.UpTrue.signals.values(:)];
    assert(isequal(size(estimated),size(truth)) && size(truth,1)==numel(t) && ...
        all(isfinite(estimated(:))) && all(isfinite(truth(:))), ...
        'RocketPlant:InvalidWeatherNavigation', ...
        'Navigation position outputs must be finite and aligned with plant truth.');
    positionError=vecnorm(estimated-truth,2,2);
    inFlight=x(:,14)>=1 & x(:,14)<=4;
    launch=inFlight & t>=Rocket.IgnitionTime & t<=Rocket.IgnitionTime+15;
    assert(any(inFlight) && any(launch),'RocketPlant:NoWeatherLaunch', ...
        'Both runs must contain logged launch and flight samples.');
    [height,apogeeIndex]=max(-x(:,3));
    [speed,speedIndex]=max(vecnorm(x(:,4:6),2,2));
    landingIndex=find(x(:,14)==5,1);
    assert(~isempty(landingIndex),'RocketPlant:NoWeatherLanding', ...
        'Both runs must include landing for the comparison.');
    metrics=struct('ApogeeHeightAGLM',height,'ApogeeTimeS',t(apogeeIndex), ...
        'ApogeeTimeSinceIgnitionS',t(apogeeIndex)-Rocket.IgnitionTime, ...
        'PeakSpeedMps',speed,'PeakSpeedTimeS',t(speedIndex), ...
        'PeakBodyRateRadps',max(vecnorm(x(inFlight,11:13),2,2)), ...
        'LandingTimeS',t(landingIndex), ...
        'LandingTimeSinceIgnitionS',t(landingIndex)-Rocket.IgnitionTime, ...
        'FlightPositionRmsErrorM',sqrt(mean(positionError(inFlight).^2)), ...
        'LaunchPeakPositionErrorM',max(positionError(launch)), ...
        'FinalPositionErrorM',positionError(end));
end
